const CATEGORIES={
 fitness:{label:'Fitness & Wellness',add:320,
  features:[['Workout library',160],['Trainer profiles',140],['Class & session booking',180],['Progress tracking',150],['Subscription plans',170],['Wearable device sync',220]],
  ai:[['AI workout recommendations',280],['Form-check computer vision',380],['AI meal planning',240],['Chatbot coach',200]]},
 dating:{label:'Dating & Relationships',add:380,
  features:[['Profile & preferences',160],['Swipe & match logic',220],['Private chat',180],['Verification badge',200],['Boosts & subscriptions',190]],
  ai:[['AI match recommendations',320],['Photo verification AI',260],['Conversation icebreaker AI',200]]},
 food:{label:'Food & Grocery Delivery',add:420,
  features:[['Restaurant/store catalog',200],['Cart & checkout',180],['Live order tracking',220],['Delivery partner app',260],['Ratings & reviews',140]],
  ai:[['AI menu recommendations',260],['Demand forecasting AI',300],['Smart route optimization',320]]},
 healthcare:{label:'Healthcare & Telemedicine',add:460,
  features:[['Patient & doctor profiles',200],['Appointment booking',180],['Video consultation',280],['Prescriptions & reports',220],['Role-based admin',200]],
  ai:[['AI symptom checker',340],['No-show prediction AI',240],['Health data insights AI',280]]},
 ecommerce:{label:'E-commerce & Marketplace',add:400,
  features:[['Product catalog',200],['Cart & checkout',180],['Multi-vendor seller portal',260],['Order management',200],['Reviews & ratings',140]],
  ai:[['AI product recommendations',280],['Visual search AI',300],['Fraud detection AI',280]]},
 education:{label:'Education & Learning',add:300,
  features:[['Course library',200],['Live or recorded classes',240],['Assignments & quizzes',180],['Student/teacher portals',220],['Progress reports',160]],
  ai:[['AI-personalized learning paths',300],['Auto-grading AI',260],['Chatbot tutor',220]]},
 realestate:{label:'Real Estate & Property',add:320,
  features:[['Property listings',180],['Map-based search',200],['Agent dashboard',200],['Lead capture',160],['Shortlist & inquiry flow',150]],
  ai:[['AI property recommendations',260],['Price estimation AI',300],['Virtual tour / AR staging',340]]},
 ride:{label:'Ride & Mobility',add:460,
  features:[['Rider app',220],['Driver app',220],['Live trip tracking',240],['Fare calculation',180],['Dispatch dashboard',220]],
  ai:[['Dynamic pricing AI',320],['ETA prediction AI',280],['Route optimization AI',300]]},
 logistics:{label:'Logistics & Fleet',add:460,
  features:[['Booking & dispatch',220],['Driver/fleet app',240],['Live shipment tracking',240],['Proof of delivery',160],['Operations dashboard',220]],
  ai:[['Route optimization AI',320],['Demand & capacity forecasting',280],['Predictive maintenance AI',300]]},
 fintech:{label:'Fintech & Banking',add:500,
  features:[['Secure onboarding & KYC',240],['Wallet & payment flows',220],['Transaction history',160],['Admin reporting',200],['Security planning',220]],
  ai:[['Fraud detection AI',360],['Spend insights AI',260],['Credit scoring AI',340]]},
 booking:{label:'Booking & Appointments',add:260,
  features:[['Booking calendar',180],['Availability rules',160],['Staff/provider profiles',180],['Payments',180],['Reminders',120]],
  ai:[['Smart scheduling AI',240],['No-show prediction AI',220],['Personalized offers AI',200]]},
 travel:{label:'Travel & Hospitality',add:380,
  features:[['Search & filters',180],['Booking flow',200],['Itinerary builder',200],['Payments',180],['Admin inventory',200]],
  ai:[['AI trip recommendations',280],['Dynamic pricing AI',300],['Chatbot concierge',240]]},
 social:{label:'Social & Community',add:380,
  features:[['Profiles',160],['Feeds or groups',220],['Messaging',200],['Moderation tools',220],['Notifications',120]],
  ai:[['Content recommendation AI',280],['AI moderation',320],['Sentiment analysis',240]]},
 streaming:{label:'Streaming & Entertainment',add:420,
  features:[['Media library',220],['Playback experience',200],['Subscriptions',180],['Creator/admin controls',220],['Analytics',160]],
  ai:[['AI content recommendations',300],['Auto-captioning AI',240],['Content moderation AI',280]]},
 business:{label:'Business & Productivity',add:340,
  features:[['Role-based workflows',220],['Task & approval flow',200],['Dashboard',200],['Notifications',120],['Admin controls',180]],
  ai:[['Workflow automation AI',300],['Predictive analytics',280],['AI report generation',260]]},
 custom:{label:'Custom / Other',add:300,
  features:[['Core user flow',180],['Admin dashboard',200],['Notifications',120],['Search & filtering',160],['Basic reporting',160]],
  ai:[['AI chatbot assistant',260],['Recommendation engine',280],['Predictive analytics',280]]}
};
module.exports = { CATEGORIES };
