const PACKAGE_TIERS={
 startup:[
  {name:'MVP Launch - Starter',price:'$500',timeline:'1 week',screens:'1-5 screens',best:'A proof of concept or very small fixed-scope MVP.',included:['Landing flow or tiny app journey','Basic UI structure','One core user action','Light QA and handoff'],not:['Backend-heavy workflows','Payment systems','Complex admin panel','Multi-role architecture']},
  {name:'MVP Launch - Basic',price:'$899',timeline:'2 weeks',screens:'5-10 screens',best:'A simple MVP with a complete user module and a fixed core flow.',included:['Login or user profile','Core app flow','Simple admin or content control','QA and app-store guidance'],not:['Advanced analytics','Multiple integrations','Marketplace logic','Ongoing support by default']},
  {name:'MVP Launch - Standard',price:'$1,199',timeline:'3 weeks',screens:'10-15 screens',best:'A small but complete first app version with clearly defined features.',included:['Multiple screens and states','User account flow','Basic notifications or data handling','Release support'],not:['Changing scope every week','Complex backend automation','Enterprise permissions','Custom AI/ML features']},
  {name:'MVP Launch - Plus',price:'$1,499',timeline:'4 weeks',screens:'15-20 screens',best:'A first usable application supporting a simple small-business workflow.',included:['Expanded workflow','Admin support','Payment or booking-ready structure','Launch checklist'],not:['Deep integrations','Large multi-module platform','SLA support','Advanced security review']},
  {name:'Startup App Audit and Improvement',price:'From $500',timeline:'1-2 weeks',screens:'Existing app',best:'An existing app needing an audit, targeted fixes, UI polish, or performance improvement.',included:['UX and flow review','Bug and stability check','Priority improvement list','Short action report'],not:['Full rebuild','Major new modules','Guaranteed store approval','Large refactor without scope']},
  {name:'Startup Maintenance and Support',price:'$899/month',timeline:'Monthly',screens:'Live app',best:'A live application requiring predictable monthly maintenance.',included:['Monthly QA checks','Minor fixes','Store-readiness checks','Support report'],not:['Major feature development','24/7 SLA unless scoped','New platform build','Deep architecture rewrite']},
  {name:'Startup Discovery and Prototype',price:'$500',timeline:'1 week',screens:'Prototype scope',best:'An unclear app idea that needs structure before development.',included:['Feature map','Clickable prototype direction','User flow outline','Package recommendation'],not:['Production development','Backend development','App-store launch','Technical architecture doc']},
  {name:'Market Launch Package',price:'$500',timeline:'1 week',screens:'Release-ready app',best:'A completed app that needs release readiness and store support.',included:['Release checklist','Store listing review','QA pass','Go-live support plan'],not:['Fixing unknown code risks','Large bug backlog','Marketing campaign','Post-launch monthly support']}
 ],
 growth:[
  {name:'Growth Basic',price:'$1,500',timeline:'4-5 weeks',screens:'20-25 screens',best:'A business needing an MVP with backend, basic admin, and standard workflows.',included:['Backend setup','Basic admin panel','User workflows','QA and release support'],not:['Advanced automation','Heavy integrations','Enterprise documentation','Dedicated monthly team']},
  {name:'Growth Standard',price:'$2,499',timeline:'6-8 weeks',screens:'25-35 screens',best:'A complete business app requiring backend, admin, payment, and moderate complexity.',included:['Payment flow','Admin dashboard','Notifications','Reporting basics'],not:['Multi-tenant platform','Advanced roles across departments','Complex compliance','Unlimited module changes']},
  {name:'Growth Advanced',price:'$3,499',timeline:'8-10 weeks',screens:'35-45 screens',best:'A feature-rich app with multiple flows, admin controls, payments, and moderate integrations.',included:['Multiple app modules','Controlled integrations','Advanced admin flows','Launch plan'],not:['Enterprise UAT process','Large data migration','Custom infrastructure','Formal SLA support']},
  {name:'Growth Plus',price:'$4,999',timeline:'10-14 weeks',screens:'45-60 screens',best:'A strong version-one product with multiple modules, backend, admin, payments, and controlled integrations.',included:['Multi-module delivery','Backend/API coordination','Release management','Handover documentation'],not:['Large enterprise platform','Regulated compliance package','Dedicated support desk','Unbounded discovery']},
  {name:'Growth App Audit and Improvement',price:'$1,500-$4,999',timeline:'2-4 weeks',screens:'Existing product',best:'An existing product that needs a structured audit, an improvement roadmap, and prioritized fixes.',included:['Technical audit','UX and performance review','Fix roadmap','Priority backlog'],not:['Full product rebuild','New product strategy','Unlimited fixes','SLA monitoring']},
  {name:'Growth Maintenance',price:'$1,500-$2,999/month',timeline:'Monthly',screens:'Live business app',best:'A live business app that needs ongoing upkeep, monitoring, and minor improvements every month.',included:['Monthly QA','Bug triage','Small improvements','Release support'],not:['Major roadmap development','New app build','Full-time dedicated team','24/7 emergency SLA']},
  {name:'Growth Discovery and Prototype',price:'$1,500-$2,999',timeline:'2-3 weeks',screens:'Prototype and flow map',best:'A business idea that needs structured discovery, flows, and a clickable prototype before development.',included:['Workshop','User journey map','Clickable prototype','Development estimate'],not:['Production app build','Backend integrations','Store launch','Monthly support']},
  {name:'Growth Launch Readiness',price:'$1,500-$2,499',timeline:'2-3 weeks',screens:'Near-complete app',best:'A near-complete app that needs QA, store readiness, and a supported release.',included:['QA pass','Store readiness','Release plan','Post-launch watchlist'],not:['Major feature build','Large bug rescue','Marketing launch','Long-term maintenance']}
 ],
 enterprise:[
  {name:'Enterprise Starter',price:'Starts from $5,000',timeline:'10-12 weeks',screens:'60-75 screens',best:'A business-critical product that needs full discovery, multiple roles, and a structured first release.',included:['Full discovery','Architecture plan','Multiple user roles','Controlled first release'],not:['Final pricing before discovery','Ongoing SLA by default','Large data migration','Custom compliance certification']},
  {name:'Enterprise Standard',price:'Indicative starting point: $6,999+',timeline:'12-16 weeks',screens:'75-100 screens',best:'A complex application with detailed documentation, technical architecture, and advanced permissions.',included:['Technical architecture','Advanced permissions','Admin operations','Handover pack'],not:['Unlimited integrations','24/7 support unless scoped','Hardware procurement','Regulatory approval']},
  {name:'Enterprise Advanced',price:'Indicative starting point: $8,499+',timeline:'16-20 weeks',screens:'100-125 screens',best:'A large product with workflow automation, advanced roles, UAT, and formal handover documentation.',included:['Workflow automation','UAT support','Documentation','Formal release plan'],not:['Final price without discovery','Massive legacy migration','Dedicated NOC unless scoped','Unbounded roadmap changes']},
  {name:'Enterprise Premium',price:'Starts from $10,000+',timeline:'20-24 weeks or more',screens:'125+ screens',best:'A complex multi-module platform requiring solution architecture, advanced workflows, and go-live support.',included:['Solution architecture','Multi-module build','Go-live support','Support model'],not:['Open-ended scope','Unapproved third-party costs','Regulatory certification','Post-launch SLA unless added']},
  {name:'Enterprise Discovery and Architecture',price:'Starts from $5,000',timeline:'3-4 weeks',screens:'Architecture package',best:'A complex product idea that needs full requirements, architecture, and a delivery roadmap before any build.',included:['Requirements discovery','Architecture blueprint','Delivery roadmap','Risk register'],not:['Production coding','App-store launch','Long-term support','Guaranteed fixed build cost before scope']},
  {name:'Enterprise App Rescue and Technical Audit',price:'Starts from $5,000',timeline:'3-5 weeks',screens:'Existing platform',best:'A struggling or at-risk application that needs a deep technical audit and a rescue roadmap.',included:['Code and architecture audit','Risk review','Rescue roadmap','Rebuild vs repair recommendation'],not:['Instant fixes without audit','Replacing every vendor issue','Production SLA','New feature roadmap by default']},
  {name:'Enterprise Maintenance and Support',price:'Starts from $5,000/month',timeline:'Monthly',screens:'Production app',best:'A production enterprise application that needs SLA-backed monthly support and monitoring.',included:['SLA-backed support','Monitoring cadence','Release coordination','Monthly reporting'],not:['New product build','Unlimited feature development','Ownership of third-party outages','Compliance certification']},
  {name:'Enterprise Launch and Go-Live',price:'Starts from $5,000',timeline:'3-4 weeks',screens:'Completed enterprise product',best:'A completed enterprise product that needs a controlled, supported production go-live.',included:['Go-live plan','Final QA coordination','Rollback planning','Post-launch monitoring'],not:['Major rebuild','Long-term support unless added','Marketing launch','Unscoped production fixes']}
 ]};
module.exports = { PACKAGE_TIERS };
